theme: jekyll-theme-minimal
title: Abraham Ruiz
description: writeups and projects.
url: https://abraham-ruiz.github.io/home # optional; remove until you set your custom domain
baseurl: "" # leave empty for user site
